---
title: "Problem Set 1"
author: "Bern DySart"
date: "2024-01-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval = TRUE,fig.align= 'center')
#load packages
library(gapminder)
library(tidyverse)
library(stargazer)
library(haven)
library(knitr)
str(gapminder_unfiltered)
```

1.There are 3,313 observations in the dataset. There are 6 variables in the dataset.gapminder_unfilterd contains data from years 1950 - 2007. Every country is covered in the data set for each year. 

```{r}
gapminder = gapminder_unfiltered
```

2. See plot below
```{r}
plot(lifeExp~year, data = gapminder,
     xlab = 'Year',
     ylab = 'Life Expectancy',
     main = 'Life Expectancy Trends')
model1 =
  lm(lifeExp ~ year, data = gapminder)
abline(model1,col = 'green', lw = 8)
```

3. See table below
```{r}
outcome =
  count(gapminder, continent)
kable(outcome)
```

4. See plot below
```{r}
p <-ggplot(gapminder, 
           aes(x = gdpPercap, y = lifeExp))
p <- p + scale_x_log10()
p + 
  geom_point(alpha = (1/3), size = 3) + 
  facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
```

5. See fixed code
```{r flights, eval = FALSE}
flights |>
  filter(dest=="IAH") |>
  group_by(year,month,day) |>
  summarize(
    n=n(), 
    delay=mean(arr_delay, na.rm=TRUE)
  ) |>
  filter(n>10)

flights |> 
  filter(carrier=="UA", 
         dest%in%c("IAH", "HOU"), 
         sched_dep_time > 0900,sched_arr_time<2000) |>
  group_by(flight) |>
  summarize(
    delay=mean(arr_delay,na.rm=TRUE),
    cancelled=sum(is.na(arr_delay)),n=n()
  ) |>
  filter(n>10)
```